
#violaslayer config

traceback_limit = 5

chain_id = 5

#btc connect 
[btc_conn]
    rpcuser="btc"
    rpcpassword="btc"
    rpcip="127.0.0.1"
    rpcport=18332

[[db_list]]
    host=["127.0.0.1:37017"]
    db="filter"
    user="violas"
    password="violas@palliums"
    authdb="admin"
    rsname="rsviolas"
        
[[db_list]]
    host=["127.0.0.1:37017"]
    db="proof"
    user="violas"
    password="violas@palliums"
    authdb="admin"
    rsname="rsviolas"

[[db_list]]
    host=["127.0.0.1:37017"]
    db="markproof"
    user="violas"
    password="violas@palliums"
    authdb="admin"
    rsname="rsviolas"

[[db_list]]
    host=["127.0.0.1:37017"]
    db="address"
    user="violas"
    password="violas@palliums"
    authdb="admin"
    rsname="rsviolas"
    

[looping_sleep]
    bfilter=1
    b2v=1
    comm=1
    markproof=1

